/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiRecipesRouteImport } from './routes/api/recipes'
import { Route as ApiPreferencesRouteImport } from './routes/api/preferences'
import { Route as ApiMealsRouteImport } from './routes/api/meals'
import { Route as ApiConstraintsRouteImport } from './routes/api/constraints'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSessionsSessionIdRouteImport } from './routes/api/sessions/$sessionId'
import { Route as ApiRecipesIdRouteImport } from './routes/api/recipes/$id'
import { Route as ApiMealsCommentRouteImport } from './routes/api/meals/comment'
import { Route as ApiMealsIdRouteImport } from './routes/api/meals/$id'
import { Route as ApiRecipesIdIllustrationRouteImport } from './routes/api/recipes/$id.illustration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesRoute = ApiRecipesRouteImport.update({
  id: '/api/recipes',
  path: '/api/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesRoute = ApiPreferencesRouteImport.update({
  id: '/api/preferences',
  path: '/api/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMealsRoute = ApiMealsRouteImport.update({
  id: '/api/meals',
  path: '/api/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConstraintsRoute = ApiConstraintsRouteImport.update({
  id: '/api/constraints',
  path: '/api/constraints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSessionIdRoute = ApiSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiRecipesIdRoute = ApiRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRecipesRoute,
} as any)
const ApiMealsCommentRoute = ApiMealsCommentRouteImport.update({
  id: '/comment',
  path: '/comment',
  getParentRoute: () => ApiMealsRoute,
} as any)
const ApiMealsIdRoute = ApiMealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMealsRoute,
} as any)
const ApiRecipesIdIllustrationRoute =
  ApiRecipesIdIllustrationRouteImport.update({
    id: '/illustration',
    path: '/illustration',
    getParentRoute: () => ApiRecipesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/constraints': typeof ApiConstraintsRoute
  '/api/meals': typeof ApiMealsRouteWithChildren
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/recipes': typeof ApiRecipesRouteWithChildren
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/meals/$id': typeof ApiMealsIdRoute
  '/api/meals/comment': typeof ApiMealsCommentRoute
  '/api/recipes/$id': typeof ApiRecipesIdRouteWithChildren
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRoute
  '/api/recipes/$id/illustration': typeof ApiRecipesIdIllustrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/constraints': typeof ApiConstraintsRoute
  '/api/meals': typeof ApiMealsRouteWithChildren
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/recipes': typeof ApiRecipesRouteWithChildren
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/meals/$id': typeof ApiMealsIdRoute
  '/api/meals/comment': typeof ApiMealsCommentRoute
  '/api/recipes/$id': typeof ApiRecipesIdRouteWithChildren
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRoute
  '/api/recipes/$id/illustration': typeof ApiRecipesIdIllustrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/constraints': typeof ApiConstraintsRoute
  '/api/meals': typeof ApiMealsRouteWithChildren
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/recipes': typeof ApiRecipesRouteWithChildren
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/meals/$id': typeof ApiMealsIdRoute
  '/api/meals/comment': typeof ApiMealsCommentRoute
  '/api/recipes/$id': typeof ApiRecipesIdRouteWithChildren
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRoute
  '/api/recipes/$id/illustration': typeof ApiRecipesIdIllustrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/constraints'
    | '/api/meals'
    | '/api/preferences'
    | '/api/recipes'
    | '/api/sessions'
    | '/api/meals/$id'
    | '/api/meals/comment'
    | '/api/recipes/$id'
    | '/api/sessions/$sessionId'
    | '/api/recipes/$id/illustration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/constraints'
    | '/api/meals'
    | '/api/preferences'
    | '/api/recipes'
    | '/api/sessions'
    | '/api/meals/$id'
    | '/api/meals/comment'
    | '/api/recipes/$id'
    | '/api/sessions/$sessionId'
    | '/api/recipes/$id/illustration'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/constraints'
    | '/api/meals'
    | '/api/preferences'
    | '/api/recipes'
    | '/api/sessions'
    | '/api/meals/$id'
    | '/api/meals/comment'
    | '/api/recipes/$id'
    | '/api/sessions/$sessionId'
    | '/api/recipes/$id/illustration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConstraintsRoute: typeof ApiConstraintsRoute
  ApiMealsRoute: typeof ApiMealsRouteWithChildren
  ApiPreferencesRoute: typeof ApiPreferencesRoute
  ApiRecipesRoute: typeof ApiRecipesRouteWithChildren
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes': {
      id: '/api/recipes'
      path: '/api/recipes'
      fullPath: '/api/recipes'
      preLoaderRoute: typeof ApiRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences': {
      id: '/api/preferences'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meals': {
      id: '/api/meals'
      path: '/api/meals'
      fullPath: '/api/meals'
      preLoaderRoute: typeof ApiMealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/constraints': {
      id: '/api/constraints'
      path: '/api/constraints'
      fullPath: '/api/constraints'
      preLoaderRoute: typeof ApiConstraintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId': {
      id: '/api/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/sessions/$sessionId'
      preLoaderRoute: typeof ApiSessionsSessionIdRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/recipes/$id': {
      id: '/api/recipes/$id'
      path: '/$id'
      fullPath: '/api/recipes/$id'
      preLoaderRoute: typeof ApiRecipesIdRouteImport
      parentRoute: typeof ApiRecipesRoute
    }
    '/api/meals/comment': {
      id: '/api/meals/comment'
      path: '/comment'
      fullPath: '/api/meals/comment'
      preLoaderRoute: typeof ApiMealsCommentRouteImport
      parentRoute: typeof ApiMealsRoute
    }
    '/api/meals/$id': {
      id: '/api/meals/$id'
      path: '/$id'
      fullPath: '/api/meals/$id'
      preLoaderRoute: typeof ApiMealsIdRouteImport
      parentRoute: typeof ApiMealsRoute
    }
    '/api/recipes/$id/illustration': {
      id: '/api/recipes/$id/illustration'
      path: '/illustration'
      fullPath: '/api/recipes/$id/illustration'
      preLoaderRoute: typeof ApiRecipesIdIllustrationRouteImport
      parentRoute: typeof ApiRecipesIdRoute
    }
  }
}

interface ApiMealsRouteChildren {
  ApiMealsIdRoute: typeof ApiMealsIdRoute
  ApiMealsCommentRoute: typeof ApiMealsCommentRoute
}

const ApiMealsRouteChildren: ApiMealsRouteChildren = {
  ApiMealsIdRoute: ApiMealsIdRoute,
  ApiMealsCommentRoute: ApiMealsCommentRoute,
}

const ApiMealsRouteWithChildren = ApiMealsRoute._addFileChildren(
  ApiMealsRouteChildren,
)

interface ApiRecipesIdRouteChildren {
  ApiRecipesIdIllustrationRoute: typeof ApiRecipesIdIllustrationRoute
}

const ApiRecipesIdRouteChildren: ApiRecipesIdRouteChildren = {
  ApiRecipesIdIllustrationRoute: ApiRecipesIdIllustrationRoute,
}

const ApiRecipesIdRouteWithChildren = ApiRecipesIdRoute._addFileChildren(
  ApiRecipesIdRouteChildren,
)

interface ApiRecipesRouteChildren {
  ApiRecipesIdRoute: typeof ApiRecipesIdRouteWithChildren
}

const ApiRecipesRouteChildren: ApiRecipesRouteChildren = {
  ApiRecipesIdRoute: ApiRecipesIdRouteWithChildren,
}

const ApiRecipesRouteWithChildren = ApiRecipesRoute._addFileChildren(
  ApiRecipesRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsSessionIdRoute: typeof ApiSessionsSessionIdRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsSessionIdRoute: ApiSessionsSessionIdRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConstraintsRoute: ApiConstraintsRoute,
  ApiMealsRoute: ApiMealsRouteWithChildren,
  ApiPreferencesRoute: ApiPreferencesRoute,
  ApiRecipesRoute: ApiRecipesRouteWithChildren,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
